# Generated by Django 6.0.4 on 2026-04-25 08:50

import django.core.validators
import django.db.models.deletion
import kyc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info_requested', 'More Info Requested')], default='draft', max_length=20)),
                ('personal_name', models.CharField(blank=True, max_length=255)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('personal_phone', models.CharField(blank=True, max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('expected_monthly_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='documents/pan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']), kyc.models.validate_file_size])),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']), kyc.models.validate_file_size])),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='documents/bank/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png']), kyc.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
